services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=minio  # Используем имя сервиса вместо localhost
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=meatway-bucket
    networks: 
      - front-internal
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks: 
      - front-internal

volumes:
  minio-data:

networks:
  front-internal:
    driver: bridge